### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by frittatelle** [frittatelle/oxycloud-frontend#7]
Required by/strictly related with #2

**Comment by sikippy** [comment]
I added the login form to dev-Vina
![image](https://user-images.githubusercontent.com/28854236/101290879-6ee83300-3837-11eb-8fc4-0546e9ec8241.png)

**Comment by sikippy** [comment]
and added routing

**Comment by Janluke0** [comment]
it can't run due to [this](https://github.com/frittatelle/oxycloud-frontend/blob/dev-Vina/src/App.js#L1).

But even removing that line this is what i see on the home
![image](https://user-images.githubusercontent.com/17701089/101357462-c0c1a500-3899-11eb-8924-b421388e9976.png)

Login page works fine.

But about FileExplorer page i think that if user is not authorized should redirect to login page.
and there is a issue on top left corner.
![image](https://user-images.githubusercontent.com/17701089/101357668-0da57b80-389a-11eb-907f-2006a21bc203.png)


PS
There are a lot of warns, maybe the problem are caused by some of them?
```

src/components/FileExplorer.js
  Line 19:8:    'Delete' is defined but never used                   no-unused-vars
  Line 31:10:   'makeStyles' is defined but never used               no-unused-vars
  Line 45:7:    'drawerWidth' is assigned a value but never used     no-unused-vars
  Line 102:13:  Expected '===' and instead saw '=='                  eqeqeq
  Line 102:25:  Expected '===' and instead saw '=='                  eqeqeq
  Line 102:37:  Expected '===' and instead saw '=='                  eqeqeq
  Line 106:22:  Expected '===' and instead saw '=='                  eqeqeq
  Line 106:35:  Expected '===' and instead saw '=='                  eqeqeq
  Line 106:47:  Expected '===' and instead saw '=='                  eqeqeq
  Line 171:20:  'setSidebarOpen' is assigned a value but never used  no-unused-vars
  Line 172:1:   'useState' is assigned a value but never used        no-unused-vars
  Line 257:15:  'classes' is assigned a value but never used         no-unused-vars
  Line 286:11:  'api' is assigned a value but never used             no-unused-vars

src/components/Header.js
  Line 12:9:   'getUser' is defined but never used                                     no-unused-vars
  Line 96:34:  Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes
  Line 99:70:  Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes

src/components/HomeScreen.js
  Line 4:15:  'FormControl' is defined but never used         no-unused-vars
  Line 4:27:  'InputLabel' is defined but never used          no-unused-vars
  Line 4:38:  'Input' is defined but never used               no-unused-vars
  Line 4:44:  'Grid' is defined but never used                no-unused-vars
  Line 4:49:  'TextField' is defined but never used           no-unused-vars
  Line 4:70:  'ButtonGroup' is defined but never used         no-unused-vars
  Line 4:83:  'Button' is defined but never used              no-unused-vars
  Line 4:90:  'InputAdornment' is defined but never used      no-unused-vars
  Line 9:7:   'logoSpace' is assigned a value but never used  no-unused-vars

src/components/Login.js
  Line 2:9:    'useQuery' is defined but never used        no-unused-vars
  Line 2:18:   'useMutation' is defined but never used     no-unused-vars
  Line 2:30:   'queryCache' is defined but never used      no-unused-vars
  Line 28:5:   Duplicate key 'display'                     no-dupe-keys
  Line 78:10:  'error' is assigned a value but never used  no-unused-vars

src/components/Router.js
  Line 1:10:  'useState' is defined but never used  no-unused-vars
  Line 6:2:   'Link' is defined but never used      no-unused-vars
  Line 7:2:   'Switch' is defined but never used    no-unused-vars
```

**Comment by sikippy** [comment]
> it can't run due to [this](https://github.com/frittatelle/oxycloud-frontend/blob/dev-Vina/src/App.js#L1).
> 
> But even removing that line this is what i see on the home
> ![image](https://user-images.githubusercontent.com/17701089/101357462-c0c1a500-3899-11eb-8924-b421388e9976.png)
> 
> Login page works fine.
> 
> But about FileExplorer page i think that if user is not authorized should redirect to login page.
> and there is a issue on top left corner.
> ![image](https://user-images.githubusercontent.com/17701089/101357668-0da57b80-389a-11eb-907f-2006a21bc203.png)
> 
> PS
> There are a lot of warns, maybe the problem are caused by some of them?
> 
> ```
> 
> src/components/FileExplorer.js
>   Line 19:8:    'Delete' is defined but never used                   no-unused-vars
>   Line 31:10:   'makeStyles' is defined but never used               no-unused-vars
>   Line 45:7:    'drawerWidth' is assigned a value but never used     no-unused-vars
>   Line 102:13:  Expected '===' and instead saw '=='                  eqeqeq
>   Line 102:25:  Expected '===' and instead saw '=='                  eqeqeq
>   Line 102:37:  Expected '===' and instead saw '=='                  eqeqeq
>   Line 106:22:  Expected '===' and instead saw '=='                  eqeqeq
>   Line 106:35:  Expected '===' and instead saw '=='                  eqeqeq
>   Line 106:47:  Expected '===' and instead saw '=='                  eqeqeq
>   Line 171:20:  'setSidebarOpen' is assigned a value but never used  no-unused-vars
>   Line 172:1:   'useState' is assigned a value but never used        no-unused-vars
>   Line 257:15:  'classes' is assigned a value but never used         no-unused-vars
>   Line 286:11:  'api' is assigned a value but never used             no-unused-vars
> 
> src/components/Header.js
>   Line 12:9:   'getUser' is defined but never used                                     no-unused-vars
>   Line 96:34:  Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes
>   Line 99:70:  Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes
> 
> src/components/HomeScreen.js
>   Line 4:15:  'FormControl' is defined but never used         no-unused-vars
>   Line 4:27:  'InputLabel' is defined but never used          no-unused-vars
>   Line 4:38:  'Input' is defined but never used               no-unused-vars
>   Line 4:44:  'Grid' is defined but never used                no-unused-vars
>   Line 4:49:  'TextField' is defined but never used           no-unused-vars
>   Line 4:70:  'ButtonGroup' is defined but never used         no-unused-vars
>   Line 4:83:  'Button' is defined but never used              no-unused-vars
>   Line 4:90:  'InputAdornment' is defined but never used      no-unused-vars
>   Line 9:7:   'logoSpace' is assigned a value but never used  no-unused-vars
> 
> src/components/Login.js
>   Line 2:9:    'useQuery' is defined but never used        no-unused-vars
>   Line 2:18:   'useMutation' is defined but never used     no-unused-vars
>   Line 2:30:   'queryCache' is defined but never used      no-unused-vars
>   Line 28:5:   Duplicate key 'display'                     no-dupe-keys
>   Line 78:10:  'error' is asesigned a value but never used  no-unused-vars
> 
> src/components/Router.js
>   Line 1:10:  'useState' is defined but never used  no-unused-vars
>   Line 6:2:   'Link' is defined but never used      no-unused-vars
>   Line 7:2:   'Switch' is defined but never used    no-unused-vars
> ```

Hi Gian, I think the issues came from unused var which should be removed, I will try to refactor the code

**Comment by sikippy** [comment]
@Janluke0, about the homescreen, I made it blue, because I don't have any ideas yet to design the homescreen. Sorry about the file explorer, I edited directly on git in this part (added by Vina bla bla bla). To go to login page, just put /Login after the domain link. I want to reconnect between homescreen and login page, but as I mentioned above, if you have some ideas, maybe? And thank you for your feedback

**Comment by Janluke0** [comment]
> I made it blue, because I don't have any ideas yet to design the homescreen. 

I remembered (from the pics you send on tg) that you did a white page with a blue button in the center so I thought that something happen anyway is not important.


>To go to login page, just put /Login 

yeah i saw it, it looks working fine. 

> if you have some ideas, maybe? 

I think that a this point of the development the home could be the main page we are working on.

**Comment by sikippy** [comment]
> > I made it blue, because I don't have any ideas yet to design the homescreen.
> 
> I remembered (from the pics you send on tg) that you did a white page with a blue button in the center so I thought that something happen anyway is not important.
> 
> > To go to login page, just put /Login
> 
> yeah i saw it, it looks working fine.
> 
> > if you have some ideas, maybe?
> 
> I think that a this point of the development the home could be the main page we are working on.

Ooh, yes, the image that I sent to the group? it was a react-native code, did you remember that I made for cross platform?as I don't have you and others replied, so I didn't use it. Do you ok, if I made just white, with a button in the center?

**Comment by Janluke0** [comment]
How you prefer, do the simplest thing, as i said it is not important.

**Comment by sikippy** [comment]
Ok, make it simplest just nice to have, thanks :)
Best Regards,

Vina P.
give your best in every challenges.

 

    On Tuesday, December 8, 2020, 12:02:28 AM GMT+7, Janluke0 <notifications@github.com> wrote:  
 
 


How you prefer, do the simplest thing, as i said it is not important.
