### ISSUE TITLE
Map icon with extension

### ISSUE THREAD

**Issue by nucciocrea9** [frittatelle/oxycloud-frontend#8]
I did a function in file explorer. i used an object with extension and icon for each extension. Then I used map() to get elements from the object and finally they are displayed in each row

**Comment by Janluke0** [comment]
That was my idea

```JS
mapping = {'image':['png', 'gif'], 'document':['docx', 'txt']}

Icons = {'image':Icona,...} 

  fun getIcon(ext) {
    for(var tipo in mapping) {
      If(mapping[tipo].indexOf(ext)>0) 
        return icons[tipo];
  }
```

and then  in JSX

```
<{getIcon(ext)}/>
```

**Comment by nucciocrea9** [comment]
The problem is when we add a file with an extensionthat is not specified in object

**Comment by nucciocrea9** [comment]
const extension=[
            { id:1, ext:"png", icon: <ImageIcon />  },
            {id:2,  ext:"txt", icon: <InsertDriveFileIcon />  },
            { id:1, ext:"jpg", icon: <ImageIcon/>  },
            { id:1, ext:"pdf", icon: <InsertDriveFileIcon /> },
            { id:1, ext:"docx", icon: <ImageIcon/> },
        ];
   
        function getExt(ext1){
           
          
                return(
                    <div>{extension.map(data=>{
                          if(ext1==data.ext){
                          return(
                          <span > {data.icon}</span>
                          )}
            //return null
                         })}
                  </div>
    )}

**Comment by Janluke0** [comment]
```JS
map = {'image':['png', 'gif'], 'document':['docx', 'txt']}

icons = {'image':'ImgIcona', 'document':'DocIcon'} 

function getIcon(ext) {
  for(var tipo in map) {
    if(map[tipo].indexOf(ext)!=-1) 
      return icons[tipo];
  }
}
```

**Comment by Janluke0** [comment]
Ready for MVP
